### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by dennissergeev** [bjlittle/geovista#145]
## 📰 Custom Issue

Hi @bjlittle! I am close to submitting a paper in which one of the figures is made using GeoVista - so naturally I would like give you credit. How would you prefer me to cite GeoVista?

Cheers!

**Comment by bjlittle** [comment]
@dennissergeev wow, okay... that's just incredible news! :open_mouth: 

First of all, thanks of using `geovista`, and secondly congrats on your paper!

I'm somewhat humbled by the fact that you're using it for your scientific work. It means a lot, particularly at the early stage of it's development.

Now that I've picked my jaw up up off the floor... I'm going to register for an ORCID, then configure Zenodo CI integration to upload `geovista` so that there's a DOI.

I'm also a heartbeat away from cutting the first minor release of `geovista`... so your timing couldn't be more perfect!

Right, I'll update you here with my progress and we can roll from there.

Cheers!

**Comment by dennissergeev** [comment]
@bjlittle Thank you! I'm happy to give you credit in whatever way you prefer!
A combination of `CITATION.cff` and Zenodo DOI would suffice, thanks for setting it up so swiftly.

I guess once the `geovista` is mature enough it would be great to see it being published in a journal like JOSS/JORS (as was [pyvista](https://joss.theoj.org/papers/10.21105/joss.01450) by the way), but I understand it's probably not as high on your priority list as for us in academia. :smile:

**Comment by bjlittle** [comment]
> @bjlittle Thank you! I'm happy to acknowledge your work in whatever way you prefer!
> A combination of `CITATION.cff` and Zenodo DOI would suffice, thanks for setting it up so swiftly.

No problem. It was on my to-do list... just didn't think it would be needed so soon :wink:, but it's certainly pushing me in the right direction, so super happy to help.

> I guess once the `geovista` is mature enough it would be great to see it being published in a journal like JOSS/JORS (as was [pyvista](https://joss.theoj.org/papers/10.21105/joss.01450) by the way), but I understand it's probably not as high on your priority list as for us in academia. smile

Yeah, I was aware that Bane et al had published a paper on JOSS for `pyvista` as the preferred citation, and that's also the route taken by `xarray` with JORS by Stephan Hoyer and Jo Hamman. Give it time and I'll make that also happen for `geovista`... just need to show it a bit more love first and mature the core features, then I'll circle back and pen a short paper :+1:

**Comment by bjlittle** [comment]
@dennissergeev All done! 

`geovista` is now citable, tagged and released, and also available on [conda-forge](https://anaconda.org/conda-forge/geovista?version=0.1.1&channel=main) and [PyPI](https://pypi.org/project/geovista/0.1.1/) :smile: 

Enjoy! 

I'm going to close this issue now :+1:

**Comment by bjlittle** [comment]
@all-contributors please add @dennissergeev for promotion

**Comment by dennissergeev** [comment]
Many thanks @bjlittle!
