### ISSUE TITLE
Python 3.11 support

### ISSUE THREAD

**Issue by dennissergeev** [bjlittle/geovista#156]
## ✨ Feature Request

Feel free to ignore this for now as this is a very minor issue, but it would be great to remove the Python version cap at 3.10. Or is there a specific reason you've capped it for now?

## Motivation

Keeping up with the pace of Python :snake: 

## Additional Context

I actually tried `geovista` in a py-3.11 environment, and it seemed to work. I haven't done any extensive testing though.

**Comment by bjlittle** [comment]
@dennissergeev Yup, top of my `todo` list👍 

I was hitting issues with `vtk` on PyPI, hence the temporary pin for now.

**Comment by dennissergeev** [comment]
Great, thanks for the prompt response! :rocket: 

Love the new badge by the way!

![status](https://img.shields.io/badge/geovista-freshly%20hatched%20%F0%9F%90%A3-success)

**Comment by bjlittle** [comment]
@dennissergeev The problem here is that due to an issue with `vtk` (PR [#3869](https://github.com/pyvista/pyvista/issues/3869)) when using `pyvista`, has forced me to temporarily rolled back from using the latest `vtk` 9.2.5 to 9.2.2.

Also, note that, `vtk` 9.2.2 landed back in Oct 2022, and as such no binary wheels were built for `py311`. See [here](https://pypi.org/project/vtk/9.2.2/#files).

So I'm kinda caught between a rock and a hard-place with regards to PyPI dependencies.

However, I'm going to relax the pin for `vtk` in the `setup.cfg`, so that the PyPI dependencies will resolve for `py311`, but users will hit issues, until they are fixed. The workaround is simply to install `geovista` with `conda` instead :wink

This approach will allow me to remove the `python` pin in the `setup.py`, and support `py311` with `conda`.

Works for me :+1:

**Comment by bjlittle** [comment]
@dennissergeev Done 👍 

![image](https://user-images.githubusercontent.com/2051656/217127316-ee5a4599-53c0-4888-accd-726168b04ca2.png)

**Comment by dennissergeev** [comment]
@bjlittle this is brilliant, thanks very much!

One more thing: does `pyvista` still need to be pinned at 0.37? I'm asking because I'd like to use the latest version (0.38.1) with the new interactive backend - [`trame`](https://docs.pyvista.org/user-guide/jupyter/trame.html#trame-jupyter).

**Comment by bjlittle** [comment]
> @bjlittle this is brilliant, thanks very much!
> 
> One more thing: does `pyvista` still need to be pinned at 0.37? I'm asking because I'd like to use the latest version (0.38.1) with the new interactive backend - [`trame`](https://docs.pyvista.org/user-guide/jupyter/trame.html#trame-jupyter).

No worries 👍

Yeah, trame is super cool. Looking forward to using it as a backend too.

The are two reasons why pyvista is temporarily pinned ATM
- pyvista 0.38.x introduced a massive performance hit (see https://github.com/pyvista/pyvista/issues/3971), but I know the fix to address this
- some colleagues at the Met Office are running a tutorial at the Bureau of Meteorology in Oz this week. The tutorial uses geovista and it would cause issues/extra work/stress to move to pyvista 0.38.x atm

So as a courtesy, I'm just holding/punning back until the end of this week, the I'll unpin pyvista 👍

It's just a timing thing, so sorry for the inconvenience 🥹

**Comment by dennissergeev** [comment]
Ah that's totally fine. Thanks for the explanation :+1: 
I can certainly wait!
