### ISSUE TITLE
Remove VTK dependency to let PyVista manage it

### ISSUE THREAD

**Issue by banesullivan** [bjlittle/geovista#376]
Many users need to install custom builds/variants of VTK and the current constraints on VTK here are too restrictive. PyVista already points to VTK as a dependency, so pointing to PyVista here should be sufficient. This will give users more flexibility when needing to install VTK under different constraints.

**Comment by bjlittle** [comment]
@banesullivan The gotcha that I've just discovered is that when I use `conda-lock` on a GH runner as part of the [ci-locks](https://github.com/bjlittle/geovista/blob/main/.github/workflows/ci-locks.yml) workflow, `conda` ends up choosing the `osmesa` variant of `vtk`, which will break all the testing when `vtk` is not included explicitly as a dependency.

I guess there is some clever `conda` resolver mechanism at play here that detects that the environment must be headless and uses `osmesa` instead of `qt`. Do you know of a way to influence this without explicitly including `vtk` as a dependency?

I guess this is why you prefer to use `pip` on `pyvista`, right?

**Comment by bjlittle** [comment]
@banesullivan Okay, I think I might have figured out a way around this after a wee bit of research, which I'm comfortable suggesting as a "reasonable" compromise.

My proposal is that we indeed remove `vtk` from the `requirements` for both `conda` (`requirements/geovista.yml`) and `pypi` (`requirements/pypi-core.txt`) for all the reasons that you cited above :+1: 

And, you've already sorted the feedstock with https://github.com/conda-forge/geovista-feedstock/pull/11 :rocket:, so we're good there :+1: 

With regards to the CI issue, the only real reason for the generation of the `conda` lock-files (`requirements/locks/*.txt`) is solely for CI and developers. Users are never going to use them. Never, ever.

When it comes to generating the lock-files we can "inject" the additional `qt` requirement at lock-file build-time using "`vtk=*=qt_*`", which is the magic `conda` incantation in the form of `<package>=<version>=<build-string>` i.e., `vtk`, with the latest version (`*`), with the latest `qt` build variant (`qt_*`). See this [stackoverflow Q&A](https://stackoverflow.com/questions/48128029/installing-specific-build-of-an-anaconda-package) and the [conda package metadata definition](https://docs.conda.io/projects/conda-build/en/stable/resources/package-spec.html#package-metadata) that unraveled the mystery.

I'm gonna give this a whirl in a draft PR to see how it looks and feels, and if we're happy and there are no gotchas I've missed from you're perspective, this might be the happy compromise :thinking:
